/**
 * Node-only repository invariants.
 *
 * These are architecture checks rather than behaviour tests: they read the
 * project's own source text, so they need a filesystem and cannot run in the
 * browser or the `jsc` shell like the portable suites in `test/`. They exist to
 * fail loudly when a boundary that reviews have already established starts to
 * erode — an engine file reaching into `node_modules`, an adapter re-inventing
 * test selection, a vendored dependency drifting from its pin, or a test suite
 * that no runner registers.
 */

import { readFile, readdir } from 'node:fs/promises';
import { assertSame } from '../harness/assert.js';
import { checkVendoredDependencies } from '../../tools/vendor/sync.js';

const REPOSITORY_ROOT = new URL('../../', import.meta.url);

/** Matches `from '…'`, `import '…'`, and `import('…')` specifiers. */
const SPECIFIER_PATTERN = /\b(?:from|import)\s*\(?\s*['"]([^'"]+)['"]/g;

/**
 * @param {string} directory Repository-relative, with a trailing slash.
 * @param {(name: string) => boolean} predicate
 * @returns {Promise<string[]>}
 */
async function listFiles(directory, predicate) {
  const entries = await readdir(new URL(directory, REPOSITORY_ROOT), {
    withFileTypes: true,
  });
  /** @type {string[]} */
  const files = [];

  for (const entry of entries) {
    if (entry.isDirectory()) {
      files.push(...(await listFiles(`${directory}${entry.name}/`, predicate)));
    } else if (predicate(entry.name)) {
      files.push(`${directory}${entry.name}`);
    }
  }

  return files.sort();
}

/**
 * @param {string} file Repository-relative path.
 * @returns {Promise<string>}
 */
function readSource(file) {
  return readFile(new URL(file, REPOSITORY_ROOT), 'utf8');
}

/**
 * @param {string} source
 * @returns {string[]}
 */
function importSpecifiers(source) {
  return [...source.matchAll(SPECIFIER_PATTERN)].map((match) => match[1]);
}

/**
 * @param {string} directory
 * @returns {Promise<Map<string, string>>}
 */
async function readJavaScript(directory) {
  const files = await listFiles(directory, (name) => name.endsWith('.js'));
  /** @type {Map<string, string>} */
  const sources = new Map();

  for (const file of files) {
    sources.set(file, await readSource(file));
  }

  return sources;
}

/**
 * The trees `.prettierignore` is allowed to exclude, and why. Anything else
 * appearing in that file — `src/` above all — is a way of quietly shrinking
 * the format check back to a subset of the project, so the contract is an
 * exact table rather than a floor.
 */
const ALLOWED_FORMAT_EXCLUSIONS = Object.freeze({
  'node_modules/': 'installed dependencies, not project source',
  'vendor/': 'generated by tools/vendor/sync.js from the pinned dependencies',
  '.superpowers/': 'local working notes, not project source',
  'test/fixtures/':
    'Test262 fixtures are guest scripts, and some are deliberately unparseable',
  'package-lock.json': 'generated by npm, which owns its bytes',
  '.github/workflows/':
    'generated by tools/ci/pipeline.js, whose byte-for-byte output ci:check owns',
  'docs/test262-report.jsonl':
    'generated by npm run test262:upstream, whose JSON lines own their bytes',
});

/**
 * Turns one Prettier CLI path argument into a matcher. Only the shapes this
 * project uses are supported: `.` for the whole repository, `dir/**\/*.ext`,
 * `dir/*.ext`, and literal paths.
 *
 * @param {string} pattern
 * @returns {RegExp}
 */
function patternToRegExp(pattern) {
  const escaped = pattern
    .replace(/[.+^${}()|[\]\\]/g, '\\$&')
    .replace(/\*\*\//g, '\u0000')
    .replace(/\*\*/g, '\u0001')
    .replace(/\*/g, '[^/]*')
    .replace(/\u0000/g, '(?:[^/]+/)*')
    .replace(/\u0001/g, '.*');

  return new RegExp(`^${escaped}$`);
}

/**
 * @param {string} file Repository-relative path.
 * @param {string} entry A `.prettierignore` line.
 * @returns {boolean}
 */
function isExcludedBy(file, entry) {
  return entry.endsWith('/') ? file.startsWith(entry) : file === entry;
}

/**
 * Resolves the *authoritative* Prettier scope: the path arguments the
 * `format` script passes to Prettier, minus whatever `.prettierignore`
 * excludes. Deriving it from the real script and the real ignore file is
 * what makes the invariants below fail when engine sources are dropped from
 * the check, however that is done.
 *
 * @returns {Promise<{
 *   script: string,
 *   exclusions: string[],
 *   covers: (file: string) => boolean,
 * }>}
 */
async function readFormatScope() {
  const manifest = JSON.parse(await readSource('package.json'));
  const script = String(manifest.scripts?.format ?? '');
  const tokens = script.split(/\s+/).filter((token) => token.length > 0);

  if (tokens[0] !== 'prettier' || !tokens.includes('--check')) {
    throw new Error(`the format script must run prettier --check: ${script}`);
  }

  const patterns = tokens
    .slice(1)
    .filter((token) => !token.startsWith('-'))
    .map((token) => token.replace(/^['"]|['"]$/g, ''));
  const exclusions = (await readIgnoreFile())
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith('#'));
  const matchers = patterns.map((pattern) =>
    pattern === '.' ? /^/ : patternToRegExp(pattern),
  );

  return {
    script,
    exclusions,
    covers: (file) =>
      matchers.some((matcher) => matcher.test(file)) &&
      !exclusions.some((entry) => isExcludedBy(file, entry)),
  };
}

/**
 * @returns {Promise<string>}
 */
async function readIgnoreFile() {
  try {
    return await readSource('.prettierignore');
  } catch {
    return '';
  }
}

export default [
  {
    name: 'engine source never imports through node_modules',
    run: async () => {
      const sources = await readJavaScript('src/');
      /** @type {string[]} */
      const offenders = [];

      for (const [file, source] of sources) {
        for (const specifier of importSpecifiers(source)) {
          if (specifier.includes('node_modules')) {
            offenders.push(`${file} -> ${specifier}`);
          }
        }
      }

      assertSame(
        offenders.join('\n'),
        '',
        'src/ must not depend on an npm install layout; import the project-owned vendored build instead',
      );
      assertSame(sources.size > 0, true, 'src/ sources were found');
    },
  },
  {
    name: 'the parser dependency is named in exactly one engine file',
    run: async () => {
      const sources = await readJavaScript('src/');
      /** @type {string[]} */
      const namingFiles = [];

      for (const [file, source] of sources) {
        const namesVendor = importSpecifiers(source).some((specifier) =>
          specifier.includes('vendor/'),
        );

        if (namesVendor) {
          namingFiles.push(file);
        }
      }

      assertSame(namingFiles.join(','), 'src/parser-dependency.js');
    },
  },
  {
    name: 'test262 adapters contribute no selection policy',
    run: async () => {
      const sources = await readJavaScript('tools/test262/adapters/');
      /** @type {string[]} */
      const offenders = [];

      for (const [file, source] of sources) {
        for (const forbidden of [
          'JSON.parse',
          'manifest.json',
          'runTest262Suite',
          '.malformed',
          "'harness'",
        ]) {
          if (source.includes(forbidden)) {
            offenders.push(`${file} contains ${forbidden}`);
          }
        }
      }

      assertSame(
        offenders.join('\n'),
        '',
        'manifest parsing, selection, and defaults belong to tools/test262/selection.js',
      );
      assertSame(sources.size >= 4, true, 'adapter sources were found');
    },
  },
  {
    name: 'every test262 adapter that reads a manifest imports the shared selection module',
    run: async () => {
      const sources = await readJavaScript('tools/test262/adapters/');
      /** @type {string[]} */
      const offenders = [];

      for (const [file, source] of sources) {
        if (!source.includes('readManifest')) {
          continue;
        }

        if (!importSpecifiers(source).includes('../selection.js')) {
          offenders.push(file);
        }
      }

      assertSame(offenders.join(','), '');
    },
  },
  {
    name: 'the vendored parser build matches the pinned dependency',
    run: async () => {
      const { problems } = await checkVendoredDependencies();

      assertSame(problems.join('\n'), '');
    },
  },
  {
    name: 'every portable suite is registered with the shared runners',
    run: async () => {
      const suites = await readSource('test/suites.js');
      const files = await listFiles('test/', (name) =>
        name.endsWith('.test.js'),
      );
      const portable = files.filter(
        (file) =>
          !file.startsWith('test/node/') && !file.startsWith('test/ci/'),
      );
      /** @type {string[]} */
      const unregistered = [];

      for (const file of portable) {
        if (!suites.includes(`'./${file.slice('test/'.length)}'`)) {
          unregistered.push(file);
        }
      }

      assertSame(unregistered.join(','), '');
      assertSame(portable.length > 0, true, 'portable suites were found');
    },
  },
  {
    name: 'every node-only suite is registered with the node runner',
    run: async () => {
      const runner = await readSource('test/run-node.js');
      const files = await listFiles('test/node/', (name) =>
        name.endsWith('.test.js'),
      );
      /** @type {string[]} */
      const unregistered = [];

      for (const file of files) {
        if (!runner.includes(`'./${file.slice('test/'.length)}'`)) {
          unregistered.push(file);
        }
      }

      assertSame(unregistered.join(','), '');
      assertSame(files.length > 0, true, 'node-only suites were found');
    },
  },
  {
    name: 'the CI contract suites are registered with their own runner and with no other',
    run: async () => {
      const contractRunner = await readSource('test/run-ci-contract.js');
      const nodeRunner = await readSource('test/run-node.js');
      const portableRegistry = await readSource('test/suites.js');
      const files = await listFiles('test/ci/', (name) =>
        name.endsWith('.test.js'),
      );
      /** @type {string[]} */
      const unregistered = [];
      /** @type {string[]} */
      const leaked = [];

      for (const file of files) {
        const specifier = `'./${file.slice('test/'.length)}'`;

        if (!contractRunner.includes(specifier)) {
          unregistered.push(file);
        }

        for (const [name, source] of [
          ['test/run-node.js', nodeRunner],
          ['test/suites.js', portableRegistry],
        ]) {
          if (importSpecifiers(source).includes(specifier.slice(1, -1))) {
            leaked.push(`${file} is imported by ${name}`);
          }
        }
      }

      assertSame(unregistered.join(','), '');
      assertSame(
        leaked.join('\n'),
        '',
        'the full CI contract must not run inside npm test/test:node; it would rerun the whole pipeline recursively',
      );
      assertSame(files.length > 0, true, 'CI contract suites were found');
    },
  },
  {
    name: 'every engine source file is inside the Prettier check scope',
    run: async () => {
      const scope = await readFormatScope();
      const files = await listFiles('src/', (name) => name.endsWith('.js'));
      const outside = files.filter((file) => !scope.covers(file));

      assertSame(
        outside.join('\n'),
        '',
        `engine sources are outside the format scope: ${scope.script}`,
      );
      assertSame(files.length > 0, true, 'engine sources were found');
    },
  },
  {
    name: 'every checked-in source, tool, test, and documentation file is inside the Prettier check scope',
    run: async () => {
      const scope = await readFormatScope();
      const files = [
        ...(await listFiles(
          'src/',
          (name) => name.endsWith('.js') || name.endsWith('.json'),
        )),
        ...(await listFiles('test/', (name) => name.endsWith('.js'))),
        ...(await listFiles(
          'tools/',
          (name) => name.endsWith('.js') || name.endsWith('.json'),
        )),
        ...(await listFiles('types/', (name) => name.endsWith('.d.ts'))),
        ...(await listFiles('docs/', (name) => name.endsWith('.md'))),
        'package.json',
        'jsconfig.json',
        'eslint.config.js',
        '.prettierrc.json',
        'README.md',
      ];
      const outside = files.filter(
        (file) => !file.startsWith('test/fixtures/') && !scope.covers(file),
      );

      assertSame(
        outside.join('\n'),
        '',
        `these files are outside the format scope: ${scope.script}`,
      );
    },
  },
  {
    name: 'the Prettier ignore file excludes only generated or guest-owned trees',
    run: async () => {
      const { exclusions } = await readFormatScope();
      const allowed = Object.keys(ALLOWED_FORMAT_EXCLUSIONS);
      const unexpected = exclusions.filter((entry) => !allowed.includes(entry));

      assertSame(
        unexpected.join('\n'),
        '',
        'only generated or guest-owned trees may sit outside the format check',
      );
      assertSame(
        [...exclusions].sort().join(','),
        [...allowed].sort().join(','),
        'the ignore file and the documented exclusions must stay in step',
      );
    },
  },
];
