/**
 * Node-only repository invariants.
 *
 * These are architecture checks rather than behaviour tests: they read the
 * project's own source text, so they need a filesystem and cannot run in the
 * browser or the `jsc` shell like the portable suites in `test/`. They exist to
 * fail loudly when a boundary that reviews have already established starts to
 * erode — an engine file reaching into `node_modules`, an adapter re-inventing
 * test selection, a vendored dependency drifting from its pin, or a test suite
 * that no runner registers.
 */

import { readFile, readdir } from 'node:fs/promises';
import { assertSame } from '../harness/assert.js';
import { checkVendoredDependencies } from '../../tools/vendor/sync.js';
import { UNICODE_VERSION } from '../../src/builtins/unicode-case-data.js';
import {
  ES5_SELECTION_FILE,
  EXCLUSION_CATEGORIES,
  parseEs5Selection,
} from '../../tools/test262/es5-selection.js';
import {
  UPSTREAM_SUBSET_FILE,
  parseUpstreamSubset,
} from '../../tools/test262/upstream.js';

const REPOSITORY_ROOT = new URL('../../', import.meta.url);

/** Matches `from '…'`, `import '…'`, and `import('…')` specifiers. */
const SPECIFIER_PATTERN = /\b(?:from|import)\s*\(?\s*['"]([^'"]+)['"]/g;

/**
 * @param {string} directory Repository-relative, with a trailing slash.
 * @param {(name: string) => boolean} predicate
 * @returns {Promise<string[]>}
 */
async function listFiles(directory, predicate) {
  const entries = await readdir(new URL(directory, REPOSITORY_ROOT), {
    withFileTypes: true,
  });
  /** @type {string[]} */
  const files = [];

  for (const entry of entries) {
    if (entry.isDirectory()) {
      files.push(...(await listFiles(`${directory}${entry.name}/`, predicate)));
    } else if (predicate(entry.name)) {
      files.push(`${directory}${entry.name}`);
    }
  }

  return files.sort();
}

/**
 * @param {string} file Repository-relative path.
 * @returns {Promise<string>}
 */
function readSource(file) {
  return readFile(new URL(file, REPOSITORY_ROOT), 'utf8');
}

/**
 * @param {string} source
 * @returns {string[]}
 */
function importSpecifiers(source) {
  return [...source.matchAll(SPECIFIER_PATTERN)].map((match) => match[1]);
}

/**
 * Quotes every RegExp metacharacter so a literal URL can be matched exactly.
 *
 * @param {string} literal
 * @returns {string}
 */
function escapeForRegExp(literal) {
  return literal.replace(/[.*+?^${}()|[\]\\]/g, '\\$&');
}

/**
 * @param {string} directory
 * @returns {Promise<Map<string, string>>}
 */
async function readJavaScript(directory) {
  const files = await listFiles(directory, (name) => name.endsWith('.js'));
  /** @type {Map<string, string>} */
  const sources = new Map();

  for (const file of files) {
    sources.set(file, await readSource(file));
  }

  return sources;
}

/**
 * The trees `.prettierignore` is allowed to exclude, and why. Anything else
 * appearing in that file — `src/` above all — is a way of quietly shrinking
 * the format check back to a subset of the project, so the contract is an
 * exact table rather than a floor.
 */
const ALLOWED_FORMAT_EXCLUSIONS = Object.freeze({
  'node_modules/': 'installed dependencies, not project source',
  'vendor/': 'generated by tools/vendor/sync.js from the pinned dependencies',
  '.superpowers/': 'local working notes, not project source',
  'test/fixtures/':
    'Test262 fixtures are guest scripts, and some are deliberately unparseable',
  'package-lock.json': 'generated by npm, which owns its bytes',
  '.github/workflows/':
    'generated by tools/ci/pipeline.js, whose byte-for-byte output ci:check owns',
  'docs/test262-report.jsonl':
    'generated by npm run test262:upstream, whose JSON lines own their bytes',
});

/**
 * Turns one Prettier CLI path argument into a matcher. Only the shapes this
 * project uses are supported: `.` for the whole repository, `dir/**\/*.ext`,
 * `dir/*.ext`, and literal paths.
 *
 * @param {string} pattern
 * @returns {RegExp}
 */
function patternToRegExp(pattern) {
  const escaped = pattern
    .replace(/[.+^${}()|[\]\\]/g, '\\$&')
    .replace(/\*\*\//g, '\u0000')
    .replace(/\*\*/g, '\u0001')
    .replace(/\*/g, '[^/]*')
    .replace(/\u0000/g, '(?:[^/]+/)*')
    .replace(/\u0001/g, '.*');

  return new RegExp(`^${escaped}$`);
}

/**
 * @param {string} file Repository-relative path.
 * @param {string} entry A `.prettierignore` line.
 * @returns {boolean}
 */
function isExcludedBy(file, entry) {
  return entry.endsWith('/') ? file.startsWith(entry) : file === entry;
}

/**
 * Resolves the *authoritative* Prettier scope: the path arguments the
 * `format` script passes to Prettier, minus whatever `.prettierignore`
 * excludes. Deriving it from the real script and the real ignore file is
 * what makes the invariants below fail when engine sources are dropped from
 * the check, however that is done.
 *
 * @returns {Promise<{
 *   script: string,
 *   exclusions: string[],
 *   covers: (file: string) => boolean,
 * }>}
 */
async function readFormatScope() {
  const manifest = JSON.parse(await readSource('package.json'));
  const script = String(manifest.scripts?.format ?? '');
  const tokens = script.split(/\s+/).filter((token) => token.length > 0);

  if (tokens[0] !== 'prettier' || !tokens.includes('--check')) {
    throw new Error(`the format script must run prettier --check: ${script}`);
  }

  const patterns = tokens
    .slice(1)
    .filter((token) => !token.startsWith('-'))
    .map((token) => token.replace(/^['"]|['"]$/g, ''));
  const exclusions = (await readIgnoreFile())
    .split('\n')
    .map((line) => line.trim())
    .filter((line) => line.length > 0 && !line.startsWith('#'));
  const matchers = patterns.map((pattern) =>
    pattern === '.' ? /^/ : patternToRegExp(pattern),
  );

  return {
    script,
    exclusions,
    covers: (file) =>
      matchers.some((matcher) => matcher.test(file)) &&
      !exclusions.some((entry) => isExcludedBy(file, entry)),
  };
}

/**
 * @returns {Promise<string>}
 */
async function readIgnoreFile() {
  try {
    return await readSource('.prettierignore');
  } catch {
    return '';
  }
}

/**
 * The files under `src/builtins/` and `src/runtime/` that sit *outside* the
 * "String built-ins never call a host String method" invariant, each with the
 * reason it is out of scope. Everything else in those two directories is in
 * scope by default, so a String source added later — under any filename — is
 * covered without anyone remembering to list it, and dropping a file out of
 * the invariant means adding a line here in a review-visible way.
 */
const HOST_STRING_INVARIANT_EXEMPTIONS = Object.freeze({
  'src/builtins/number-format.js':
    'Number formatting builds and slices its own host digit strings, which are engine-internal scratch, never guest String semantics',
  'src/runtime/conversion.js':
    'ToNumber pre-dates this invariant and still trims/slices guest strings with host methods; tightening it is its own change',
});

/**
 * The Test262 upstream subset groups a milestone report depends on to say
 * which parts of the language it covers. `parseUpstreamSubset` only requires
 * *some* non-empty groups; it does not know any particular group's name is
 * load-bearing. Without this list, deleting, renaming, or emptying one of
 * these groups would still leave `tools/test262/upstream-subset.json`
 * well-formed and `npm run test262:upstream` green — just quieter, and
 * silently no longer measuring the family the README's milestone report
 * claims it does. Each entry names the milestone that pinned the group, so a
 * future milestone extends this list rather than guessing whether a group is
 * load-bearing.
 */
const REQUIRED_TEST262_GROUPS = Object.freeze({
  'built-ins/Array':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/built-ins/Array',
  'built-ins/Boolean':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/built-ins/Boolean',
  'built-ins/Error':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/built-ins/Error',
  'built-ins/Function':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/built-ins/Function',
  'built-ins/JSON':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/built-ins/JSON',
  'built-ins/Math':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/built-ins/Math',
  'built-ins/NativeErrors':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/built-ins/NativeErrors',
  'built-ins/Number':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/built-ins/Number',
  'built-ins/Object':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/built-ins/Object',
  'built-ins/RegExp':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/built-ins/RegExp',
  'built-ins/String':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/built-ins/String',
  'built-ins/ThrowTypeError':
    'ES5 completion milestone (Task 4) — the %ThrowTypeError% intrinsic (a Task 5 DEFECT cluster lives here)',
  'built-ins/decodeURI':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/built-ins/decodeURI',
  'built-ins/decodeURIComponent':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/built-ins/decodeURIComponent',
  'built-ins/encodeURI':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/built-ins/encodeURI',
  'built-ins/encodeURIComponent':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/built-ins/encodeURIComponent',
  'built-ins/isFinite':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/built-ins/isFinite',
  'built-ins/isNaN':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/built-ins/isNaN',
  'built-ins/parseFloat':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/built-ins/parseFloat',
  'built-ins/parseInt':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/built-ins/parseInt',
  'language/arguments-object':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/language/arguments-object',
  'language/eval-code':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/language/eval-code',
  'language/expressions':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/language/expressions',
  'language/function-code':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/language/function-code',
  'language/identifiers':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/language/identifiers (a Task 5 DEFECT cluster lives here)',
  'language/literals':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/language/literals',
  'language/statements':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/language/statements (Task 5 DEFECT clusters live here)',
  'language/types':
    'ES5 completion milestone (Task 4) — broad ES5.1 selection over test/language/types',
});

/** Reference documents that must exist under docs/ after reorganization. */
const REFERENCE_DOCS = Object.freeze([
  'docs/architecture.md',
  'docs/testing.md',
  'docs/conformance.md',
  'docs/limitations.md',
]);

/**
 * Returns the repository-relative file paths of the current-documentation
 * Markdown files: README.md plus any *.md files directly under docs/ that are
 * not inside the historical docs/superpowers/ subtree.
 *
 * @returns {Promise<string[]>}
 */
async function currentDocumentationFiles() {
  /** @type {string[]} */
  const files = ['README.md'];

  let entries;
  try {
    entries = await readdir(new URL('docs/', REPOSITORY_ROOT), {
      withFileTypes: true,
    });
  } catch {
    return files;
  }

  for (const entry of entries) {
    if (!entry.isDirectory() && entry.name.endsWith('.md')) {
      files.push(`docs/${entry.name}`);
    }
  }

  return files.sort();
}

/**
 * Extracts the repository-relative path of every local file referenced by a
 * Markdown link in `source`.  Anchor-only links and http(s) URLs are skipped.
 * The returned paths are resolved relative to `sourceFile`.
 *
 * @param {string} source Markdown source text.
 * @param {string} sourceFile Repository-relative path of the containing file.
 * @returns {string[]}
 */
function markdownLinkTargets(source, sourceFile) {
  const LINK_PATTERN = /\]\(([^)]+)\)/g;
  const sourceUrl = new URL(sourceFile, REPOSITORY_ROOT);
  /** @type {Set<string>} */
  const targets = new Set();

  for (const match of source.matchAll(LINK_PATTERN)) {
    const raw = match[1].trim();
    if (raw.startsWith('http://') || raw.startsWith('https://')) continue;
    if (raw.startsWith('#')) continue;
    const filePart = raw.split('#')[0];
    if (!filePart) continue;
    if (filePart.includes(' ')) continue;

    const resolved = new URL(filePart, sourceUrl);
    const rootPath = REPOSITORY_ROOT.pathname;
    if (resolved.pathname.startsWith(rootPath)) {
      targets.add(resolved.pathname.slice(rootPath.length));
    }
  }

  return [...targets];
}

/**
 * Extracts the script names from every `npm run <script>` occurrence in
 * `source`, de-duplicated and in order of first appearance.
 *
 * @param {string} source
 * @returns {string[]}
 */
function extractNpmRunCommands(source) {
  const COMMAND_PATTERN = /\bnpm run ([\w:]+)/g;
  const seen = new Set([...source.matchAll(COMMAND_PATTERN)].map((m) => m[1]));
  return [...seen];
}

/**
 * @param {string} repoRelativePath
 * @returns {Promise<boolean>}
 */
async function fileExists(repoRelativePath) {
  try {
    await readFile(new URL(repoRelativePath, REPOSITORY_ROOT), 'utf8');
    return true;
  } catch {
    return false;
  }
}

export default [
  {
    // The generated case data records the Unicode version it was built from.
    // If `package.json`'s pin moves without a regeneration (or the other way
    // round), every case mapping in the engine silently belongs to a
    // different Unicode release than the one the project claims. The portable
    // suite asserts the module's own constant; only this node-only check can
    // read the manifest, and it does so with `fs` rather than a JSON import
    // so the portable suites keep no dependency on import assertions.
    name: 'the generated Unicode case data matches the version pinned in package.json',
    run: async () => {
      const manifest = JSON.parse(await readSource('package.json'));
      const pin = manifest.unicode;

      assertSame(
        typeof pin?.version,
        'string',
        'package.json must pin a Unicode version',
      );
      assertSame(
        UNICODE_VERSION,
        pin.version,
        'src/builtins/unicode-case-data.js must be regenerated when the Unicode pin moves',
      );
      // The download URL carries the version too, so a half-updated pin is a
      // failure rather than a silent fetch of the wrong release.
      assertSame(
        String(pin.baseUrl).includes(`/${pin.version}/`),
        true,
        `the Unicode baseUrl must name the pinned version: ${pin.baseUrl}`,
      );
      assertSame(
        pin.generatedModule,
        'src/builtins/unicode-case-data.js',
        'the pin must name the module this check reads',
      );

      const generated = await readSource(pin.generatedModule);

      assertSame(
        generated.includes(pin.baseUrl),
        true,
        'the generated module header must record the pinned UCD base URL',
      );
      assertSame(
        generated.includes(`export const UNICODE_VERSION = '${pin.version}'`),
        true,
        'the generated module must export the pinned Unicode version',
      );

      // `npm run unicode:check` re-derives the tables from the UCD itself, so
      // it needs the network and cannot be a CI job. This is the offline half
      // of the same guarantee: every file the pin names must appear in the
      // header under the pinned base URL, with a well-formed sha256 digest
      // line, and the header must record *exactly* that set — no fewer, no
      // stale extras. Adding, removing, renaming, or repointing a source file
      // without regenerating therefore fails `npm run test:node`, with no
      // download and no UCD copy vendored into the repository. This is a
      // self-consistency check between the pin and the header shape, not a
      // content check: without a local copy of the UCD to hash, it cannot
      // confirm a recorded digest's *value* is the correct one for the file
      // it names.
      const files = pin.files;

      assertSame(
        typeof files === 'object' && files !== null,
        true,
        'package.json must pin the UCD file names',
      );
      assertSame(
        Object.keys(files).length > 0,
        true,
        'package.json must pin at least one UCD file',
      );

      for (const fileName of Object.values(files)) {
        const url = `${pin.baseUrl}${fileName}`;
        const digest = new RegExp(
          `${escapeForRegExp(url)}\\n \\* {5}sha256 [0-9a-f]{64}\\n`,
        );

        assertSame(
          digest.test(generated),
          true,
          `${pin.generatedModule}'s header must record ${url} with its sha256 digest; rerun npm run unicode:generate`,
        );
      }

      // The loop above only proves every *pinned* file is present; it does not
      // by itself prove nothing *else* is. A stale entry left behind by a
      // rename or a removed file — still digest-shaped, so it would satisfy
      // the pattern above for whichever file happens to still match — would
      // otherwise go unnoticed. Counting every digest-shaped header line and
      // requiring the count equal exactly the number of pinned files closes
      // that gap: it fails if the header carries more entries than the pin
      // does, exactly as it already fails if it carries fewer.
      const headerDigestLines =
        generated.match(/\n \* {5}sha256 [0-9a-f]{64}\n/g) ?? [];

      assertSame(
        headerDigestLines.length,
        Object.keys(files).length,
        `${pin.generatedModule}'s header must record exactly the ${
          Object.keys(files).length
        } UCD file(s) package.json pins — found ${
          headerDigestLines.length
        } digest entries; rerun npm run unicode:generate`,
      );
    },
  },
  {
    name: 'engine source never imports through node_modules',
    run: async () => {
      const sources = await readJavaScript('src/');
      /** @type {string[]} */
      const offenders = [];

      for (const [file, source] of sources) {
        for (const specifier of importSpecifiers(source)) {
          if (specifier.includes('node_modules')) {
            offenders.push(`${file} -> ${specifier}`);
          }
        }
      }

      assertSame(
        offenders.join('\n'),
        '',
        'src/ must not depend on an npm install layout; import the project-owned vendored build instead',
      );
      assertSame(sources.size > 0, true, 'src/ sources were found');
    },
  },
  {
    name: 'the parser dependency is named in exactly one engine file',
    run: async () => {
      const sources = await readJavaScript('src/');
      /** @type {string[]} */
      const namingFiles = [];

      for (const [file, source] of sources) {
        const namesVendor = importSpecifiers(source).some((specifier) =>
          specifier.includes('vendor/'),
        );

        if (namesVendor) {
          namingFiles.push(file);
        }
      }

      assertSame(namingFiles.join(','), 'src/parser-dependency.js');
    },
  },
  {
    name: 'test262 adapters contribute no selection policy',
    run: async () => {
      const sources = await readJavaScript('tools/test262/adapters/');
      /** @type {string[]} */
      const offenders = [];

      for (const [file, source] of sources) {
        for (const forbidden of [
          'JSON.parse',
          'manifest.json',
          'runTest262Suite',
          '.malformed',
          "'harness'",
        ]) {
          if (source.includes(forbidden)) {
            offenders.push(`${file} contains ${forbidden}`);
          }
        }
      }

      assertSame(
        offenders.join('\n'),
        '',
        'manifest parsing, selection, and defaults belong to tools/test262/selection.js',
      );
      assertSame(sources.size >= 4, true, 'adapter sources were found');
    },
  },
  {
    name: 'every test262 adapter that reads a manifest imports the shared selection module',
    run: async () => {
      const sources = await readJavaScript('tools/test262/adapters/');
      /** @type {string[]} */
      const offenders = [];

      for (const [file, source] of sources) {
        if (!source.includes('readManifest')) {
          continue;
        }

        if (!importSpecifiers(source).includes('../selection.js')) {
          offenders.push(file);
        }
      }

      assertSame(offenders.join(','), '');
    },
  },
  {
    // `parseUpstreamSubset` proves the manifest is well-formed; it has no
    // opinion on which named groups must exist. Without this check, deleting
    // or emptying one of the groups a milestone report names would still pass
    // schema validation and produce a green, merely smaller, `test262:upstream`
    // run — exactly the gap a milestone report's own claims must not have.
    name: 'every group a milestone report depends on still exists in the upstream subset',
    run: async () => {
      const subset = parseUpstreamSubset(
        await readSource(UPSTREAM_SUBSET_FILE),
      );
      const groupsByName = new Map(
        subset.groups.map((group) => [group.name, group]),
      );

      for (const [name, reason] of Object.entries(REQUIRED_TEST262_GROUPS)) {
        const group = groupsByName.get(name);

        assertSame(
          group !== undefined,
          true,
          `${UPSTREAM_SUBSET_FILE} must keep a "${name}" group (${reason}); it was removed or renamed`,
        );
        assertSame(
          (group?.paths.length ?? 0) > 0,
          true,
          `${UPSTREAM_SUBSET_FILE}'s "${name}" group must not be emptied (${reason})`,
        );
      }
    },
  },
  {
    // The coverage numbers the README publishes are generated into a marked
    // block and drift-checked against a fresh run. The exclusion tally is not:
    // it is prose a human wrote, describing how much of the upstream suite this
    // selection sets aside and why. Prose that quotes a count rots the moment
    // the policy changes, and a stale tally is worse than no tally, because it
    // reads as measured. Bind it to the policy file instead.
    name: 'the exclusion tally the README publishes matches the selection policy',
    run: async () => {
      const policy = parseEs5Selection(await readSource(ES5_SELECTION_FILE));
      const readme = await readSource('README.md');
      const counts = new Map(
        EXCLUSION_CATEGORIES.map((category) => [category, 0]),
      );

      for (const exclusion of policy.exclusions) {
        counts.set(
          exclusion.category,
          (counts.get(exclusion.category) ?? 0) + 1,
        );
      }

      for (const [category, count] of counts) {
        const row = new RegExp(
          String.raw`^\|\s*\x60${category}\x60\s*\|\s*(\d+)\s*\|`,
          'mu',
        ).exec(readme);

        assertSame(
          row !== null,
          true,
          `README.md must keep a tally row for the ${category} exclusion category`,
        );
        assertSame(
          Number(row?.[1]),
          count,
          `README.md says ${String(row?.[1])} ${category} exclusions; ${ES5_SELECTION_FILE} has ${count}`,
        );
      }

      const total = policy.exclusions.length;

      assertSame(
        readme.includes(`The ${total} classified exclusions`),
        true,
        `README.md must report ${total} classified exclusions, the total in ${ES5_SELECTION_FILE}`,
      );
    },
  },
  {
    name: 'the vendored parser build matches the pinned dependency',
    run: async () => {
      const { problems } = await checkVendoredDependencies();

      assertSame(problems.join('\n'), '');
    },
  },
  {
    name: 'every portable suite is registered with the shared runners',
    run: async () => {
      const suites = await readSource('test/suites.js');
      const files = await listFiles('test/', (name) =>
        name.endsWith('.test.js'),
      );
      const portable = files.filter(
        (file) =>
          !file.startsWith('test/node/') && !file.startsWith('test/ci/'),
      );
      /** @type {string[]} */
      const unregistered = [];

      for (const file of portable) {
        if (!suites.includes(`'./${file.slice('test/'.length)}'`)) {
          unregistered.push(file);
        }
      }

      assertSame(unregistered.join(','), '');
      assertSame(portable.length > 0, true, 'portable suites were found');
    },
  },
  {
    name: 'every node-only suite is registered with the node runner',
    run: async () => {
      const runner = await readSource('test/run-node.js');
      const files = await listFiles('test/node/', (name) =>
        name.endsWith('.test.js'),
      );
      /** @type {string[]} */
      const unregistered = [];

      for (const file of files) {
        if (!runner.includes(`'./${file.slice('test/'.length)}'`)) {
          unregistered.push(file);
        }
      }

      assertSame(unregistered.join(','), '');
      assertSame(files.length > 0, true, 'node-only suites were found');
    },
  },
  {
    name: 'the CI contract suites are registered with their own runner and with no other',
    run: async () => {
      const contractRunner = await readSource('test/run-ci-contract.js');
      const nodeRunner = await readSource('test/run-node.js');
      const portableRegistry = await readSource('test/suites.js');
      const files = await listFiles('test/ci/', (name) =>
        name.endsWith('.test.js'),
      );
      /** @type {string[]} */
      const unregistered = [];
      /** @type {string[]} */
      const leaked = [];

      for (const file of files) {
        const specifier = `'./${file.slice('test/'.length)}'`;

        if (!contractRunner.includes(specifier)) {
          unregistered.push(file);
        }

        for (const [name, source] of [
          ['test/run-node.js', nodeRunner],
          ['test/suites.js', portableRegistry],
        ]) {
          if (importSpecifiers(source).includes(specifier.slice(1, -1))) {
            leaked.push(`${file} is imported by ${name}`);
          }
        }
      }

      assertSame(unregistered.join(','), '');
      assertSame(
        leaked.join('\n'),
        '',
        'the full CI contract must not run inside npm test/test:node; it would rerun the whole pipeline recursively',
      );
      assertSame(files.length > 0, true, 'CI contract suites were found');
    },
  },
  {
    // The String built-ins must not implement guest semantics by calling the
    // host methods they are reimplementing. Behavioural tests cannot catch
    // this (host `String.prototype.charCodeAt`/`slice` return the *right*
    // answers), so the boundary is enforced against the source text: the
    // String family may read code units by index and length, and may use
    // exactly one host primitive -- `String.fromCharCode`, isolated in
    // `src/runtime/code-units.js`.
    name: 'the String built-ins never delegate to a host String.prototype method',
    run: async () => {
      // Scope by *directory*, not by filename: every `.js` file under
      // `src/builtins/` and `src/runtime/` is checked unless it appears in
      // the exemption table above with a reason. A String source added later
      // therefore cannot escape the invariant by being named something else.
      const candidates = [
        ...(await listFiles('src/builtins/', (name) => name.endsWith('.js'))),
        ...(await listFiles('src/runtime/', (name) => name.endsWith('.js'))),
      ].sort();
      const exempt = Object.keys(HOST_STRING_INVARIANT_EXEMPTIONS);
      const stale = exempt.filter((file) => !candidates.includes(file));
      const files = candidates.filter((file) => !exempt.includes(file));

      assertSame(
        stale.join('\n'),
        '',
        'an exemption names a file that no longer exists; delete the entry',
      );
      assertSame(
        files.includes('src/builtins/primitive-wrappers.js') &&
          files.includes('src/builtins/string-pattern.js') &&
          files.includes('src/runtime/code-units.js'),
        true,
        'the String built-in sources must be inside the invariant',
      );
      assertSame(files.length > 5, true, 'engine sources were found');
      const hostMethodCall =
        /\.(charAt|charCodeAt|codePointAt|concat|slice|substring|substr|indexOf|lastIndexOf|split|replace|search|match|trim|toLowerCase|toUpperCase|toLocaleLowerCase|toLocaleUpperCase|localeCompare|repeat|padStart|padEnd|startsWith|endsWith|includes|normalize)\s*\(/g;
      /** @type {string[]} */
      const offenders = [];
      /** @type {string[]} */
      const hostConstructors = [];

      for (const file of files) {
        const source = await readSource(file);
        const code = source.replace(/\/\*[\s\S]*?\*\/|\/\/[^\n]*/g, '');

        for (const match of code.matchAll(hostMethodCall)) {
          offenders.push(`${file} calls .${match[1]}()`);
        }

        if (code.includes('String.prototype')) {
          offenders.push(`${file} names String.prototype in code`);
        }

        hostConstructors.push(
          ...(code.match(/String\.fromCharCode\s*\(/g) ?? []).map(() => file),
        );
      }

      assertSame(
        offenders.join('\n'),
        '',
        'the String built-ins must own their code-unit reads instead of calling host String methods',
      );
      assertSame(
        hostConstructors.join(','),
        'src/runtime/code-units.js',
        'the number -> code-unit host primitive must stay isolated in src/runtime/code-units.js, used exactly once',
      );
    },
  },
  {
    // Regular expressions are the second (and only other) place this engine
    // deliberately borrows a host primitive instead of reimplementing it:
    // `regexp-compat.js` compiles a validated ES5 pattern into a host regex
    // rather than shipping a hand-written backtracking matcher. That
    // borrowing must stay isolated to that one file for guest-visible
    // regular expression semantics -- everywhere else, a reference to the
    // host `RegExp` constructor would either bypass `regexp-syntax.js`'s
    // grammar validation or silently reintroduce a second, divergent regex
    // dialect. (Engine-internal host regex literals, such as the numeric
    // recognisers in `conversion.js`'s `ToNumber`, are not guest-visible
    // and are outside this invariant's scope.)
    name: 'the host RegExp constructor must stay isolated in src/runtime/regexp-compat.js',
    run: async () => {
      const files = await listFiles('src/', (name) => name.endsWith('.js'));
      const hostRegExpConstructorCall = /(?:^|[^A-Za-z0-9_$])RegExp\s*\(/g;
      /** @type {string[]} */
      const matches = [];

      for (const file of files) {
        const source = await readSource(file);
        const code = source.replace(/\/\*[\s\S]*?\*\/|\/\/[^\n]*/g, '');

        if (hostRegExpConstructorCall.test(code)) {
          matches.push(file);
        }

        hostRegExpConstructorCall.lastIndex = 0;
      }

      assertSame(files.length > 5, true, 'engine sources were found');
      assertSame(
        matches.join(','),
        'src/runtime/regexp-compat.js',
        'the host RegExp constructor must stay isolated in src/runtime/regexp-compat.js, used exactly once',
      );
    },
  },
  {
    name: 'every engine source file is inside the Prettier check scope',
    run: async () => {
      const scope = await readFormatScope();
      const files = await listFiles('src/', (name) => name.endsWith('.js'));
      const outside = files.filter((file) => !scope.covers(file));

      assertSame(
        outside.join('\n'),
        '',
        `engine sources are outside the format scope: ${scope.script}`,
      );
      assertSame(files.length > 0, true, 'engine sources were found');
    },
  },
  {
    name: 'every checked-in source, tool, test, and documentation file is inside the Prettier check scope',
    run: async () => {
      const scope = await readFormatScope();
      const files = [
        ...(await listFiles(
          'src/',
          (name) => name.endsWith('.js') || name.endsWith('.json'),
        )),
        ...(await listFiles('test/', (name) => name.endsWith('.js'))),
        ...(await listFiles(
          'tools/',
          (name) => name.endsWith('.js') || name.endsWith('.json'),
        )),
        ...(await listFiles('types/', (name) => name.endsWith('.d.ts'))),
        ...(await listFiles('docs/', (name) => name.endsWith('.md'))),
        'package.json',
        'jsconfig.json',
        'eslint.config.js',
        '.prettierrc.json',
        'README.md',
      ];
      const outside = files.filter(
        (file) => !file.startsWith('test/fixtures/') && !scope.covers(file),
      );

      assertSame(
        outside.join('\n'),
        '',
        `these files are outside the format scope: ${scope.script}`,
      );
    },
  },
  {
    name: 'the Prettier ignore file excludes only generated or guest-owned trees',
    run: async () => {
      const { exclusions } = await readFormatScope();
      const allowed = Object.keys(ALLOWED_FORMAT_EXCLUSIONS);
      const unexpected = exclusions.filter((entry) => !allowed.includes(entry));

      assertSame(
        unexpected.join('\n'),
        '',
        'only generated or guest-owned trees may sit outside the format check',
      );
      assertSame(
        [...exclusions].sort().join(','),
        [...allowed].sort().join(','),
        'the ignore file and the documented exclusions must stay in step',
      );
    },
  },
  {
    // The reorganization plan creates four authoritative reference files.
    // This test fails until Tasks 2–4 create those files.
    name: 'the four reference documentation files exist under docs/',
    run: async () => {
      for (const doc of REFERENCE_DOCS) {
        assertSame(
          await fileExists(doc),
          true,
          `${doc} must exist; run the documentation reorganization tasks`,
        );
      }
    },
  },
  {
    // Every relative link that appears in a current-documentation Markdown
    // file must point to an existing file in the repository.  External http(s)
    // URLs and same-page anchors are out of scope.  Historical files under
    // docs/superpowers/ are project records, not current documentation, so
    // they are excluded from both the source scan and the target allowlist.
    name: 'every local Markdown link in current documentation resolves to an existing file',
    run: async () => {
      const docFiles = await currentDocumentationFiles();
      /** @type {string[]} */
      const broken = [];

      for (const docFile of docFiles) {
        const source = await readSource(docFile);

        for (const target of markdownLinkTargets(source, docFile)) {
          if (!(await fileExists(target))) {
            broken.push(`${docFile} -> ${target}`);
          }
        }
      }

      assertSame(
        broken.join('\n'),
        '',
        'broken local links in current documentation',
      );
      assertSame(
        docFiles.length > 0,
        true,
        'current documentation files were found',
      );
    },
  },
  {
    // Every `npm run <script>` command that appears in a current-documentation
    // Markdown file must name a script that exists in package.json.  Stale
    // command references in README or the reference docs would send readers to
    // a command that no longer works.  Historical files under docs/superpowers/
    // are excluded — they may reference commands from earlier iterations of the
    // project.
    name: 'every npm run command in current documentation refers to an existing script',
    run: async () => {
      const manifest = JSON.parse(await readSource('package.json'));
      const scripts = new Set(Object.keys(manifest.scripts ?? {}));
      const docFiles = await currentDocumentationFiles();
      /** @type {string[]} */
      const unknown = [];

      for (const docFile of docFiles) {
        const source = await readSource(docFile);

        for (const command of extractNpmRunCommands(source)) {
          if (!scripts.has(command)) {
            unknown.push(`${docFile}: npm run ${command}`);
          }
        }
      }

      assertSame(
        unknown.join('\n'),
        '',
        'current documentation references npm scripts that do not exist in package.json',
      );
    },
  },
];
