/**
 * The project's CI pipeline, as data.
 *
 * `.github/workflows/ci.yml` is a generated artifact of this module, the same
 * way `vendor/` is a generated artifact of `tools/vendor/sync.js`: the
 * workflow file is never hand-authored YAML a test pattern-matches against,
 * it is the byte-for-byte output of `renderWorkflowYaml`. That keeps "what CI
 * runs" a single structured source any test or reviewer can read, instead of
 * two documents (a workflow file and a description of it) that can drift
 * apart.
 *
 * Every job installs dependencies the same way (`actions/checkout`,
 * `actions/setup-node`, `npm ci`) and then runs one or two npm scripts, so
 * "which command does job X run" is always answerable by reading `CI_JOBS`
 * rather than the rendered YAML.
 *
 * Usage: `node tools/ci/pipeline.js` writes `.github/workflows/ci.yml` if it
 * has drifted from what this module renders; `node tools/ci/pipeline.js
 * --check` reports drift without writing, for CI or a pre-commit check.
 */

import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { pathToFileURL } from 'node:url';

/**
 * @typedef {{ uses: string, with?: Readonly<Record<string, string>> }} UsesStep
 * @typedef {{ name: string, run: string }} RunStep
 * @typedef {UsesStep | RunStep} WorkflowStep
 *
 * @typedef {{
 *   id: string,
 *   name: string,
 *   needs: readonly string[],
 *   steps: readonly WorkflowStep[],
 * }} WorkflowJob
 */

const REPOSITORY_ROOT = new URL('../../', import.meta.url);
const WORKFLOW_FILE = '.github/workflows/ci.yml';
const NODE_VERSION = '20';

/** Every job runs the same three setup steps before its own work. */
const SETUP_STEPS = Object.freeze(
  /** @type {readonly WorkflowStep[]} */ ([
    Object.freeze({ uses: 'actions/checkout@v4' }),
    Object.freeze({
      uses: 'actions/setup-node@v4',
      with: Object.freeze({ 'node-version': NODE_VERSION, cache: 'npm' }),
    }),
    Object.freeze({ name: 'Install dependencies', run: 'npm ci' }),
  ]),
);

/**
 * @param {string} id
 * @param {string} name
 * @param {readonly RunStep[]} ownSteps
 * @param {readonly string[]} [needs]
 * @returns {WorkflowJob}
 */
function job(id, name, ownSteps, needs = []) {
  return Object.freeze({
    id,
    name,
    needs: Object.freeze([...needs]),
    steps: Object.freeze([...SETUP_STEPS, ...ownSteps]),
  });
}

/**
 * @param {string} name
 * @param {string} run
 * @returns {RunStep}
 */
function step(name, run) {
  return Object.freeze({ name, run });
}

/**
 * The six checks the plan requires as distinct jobs (formatting, linting,
 * type checking, Node tests, browser tests, the pinned Test262 subset), plus
 * a `vendor` job gating the rest: every job's `npm ci` already runs vendor
 * sync through the `prepare` lifecycle script, so a dedicated, read-only
 * `vendor:check` job is what actually verifies the vendored parser build
 * still matches the pinned dependency before anything else spends CI time.
 *
 * @type {readonly WorkflowJob[]}
 */
export const CI_JOBS = Object.freeze([
  job('vendor', 'Vendor integrity', [
    step('Check vendored dependencies', 'npm run vendor:check'),
  ]),
  job('format', 'Formatting', [step('Check formatting', 'npm run format')]),
  job('lint', 'Lint', [step('Lint', 'npm run lint')]),
  job('typecheck', 'Type check', [step('Type check', 'npm run typecheck')]),
  job(
    'test-node',
    'Node tests',
    [step('Run Node suites', 'npm run test:node')],
    ['vendor'],
  ),
  job(
    'test-browser',
    'Browser tests',
    [
      step(
        'Install Playwright Chromium',
        'npx playwright install --with-deps chromium --only-shell',
      ),
      step('Run browser suites', 'npm run test:browser'),
    ],
    ['vendor'],
  ),
  job(
    'test262-subset',
    'Pinned Test262 subset',
    [step('Run pinned Test262 subset', 'npm run test262:subset')],
    ['vendor'],
  ),
]);

/**
 * @param {readonly WorkflowJob[]} [jobs]
 * @returns {string}
 */
export function renderWorkflowYaml(jobs = CI_JOBS) {
  const lines = [
    '# Generated by tools/ci/pipeline.js — do not hand edit.',
    '# Regenerate with `npm run ci:generate`; verify with `node tools/ci/pipeline.js --check`.',
    'name: CI',
    '',
    'on:',
    '  push:',
    '    branches: [main]',
    '  pull_request:',
    '',
    'jobs:',
  ];

  jobs.forEach((workflowJob, index) => {
    lines.push(`  ${workflowJob.id}:`);
    lines.push(`    name: ${workflowJob.name}`);
    lines.push('    runs-on: ubuntu-latest');

    if (workflowJob.needs.length > 0) {
      lines.push(`    needs: [${workflowJob.needs.join(', ')}]`);
    }

    lines.push('    steps:');

    for (const workflowStep of workflowJob.steps) {
      lines.push(...renderStep(workflowStep));
    }

    if (index < jobs.length - 1) {
      lines.push('');
    }
  });

  return `${lines.join('\n')}\n`;
}

/**
 * @param {WorkflowStep} workflowStep
 * @returns {string[]}
 */
function renderStep(workflowStep) {
  if ('uses' in workflowStep) {
    const lines = [`      - uses: ${workflowStep.uses}`];

    if (workflowStep.with !== undefined) {
      lines.push('        with:');

      for (const [key, value] of Object.entries(workflowStep.with)) {
        lines.push(`          ${key}: '${value}'`);
      }
    }

    return lines;
  }

  return [
    `      - name: ${workflowStep.name}`,
    `        run: ${workflowStep.run}`,
  ];
}

/**
 * Every `npm run <script>` command any job declares, deduplicated and
 * sorted, so a caller can cross-check each one against `package.json`
 * without re-parsing YAML or grepping rendered text.
 *
 * @param {readonly WorkflowJob[]} [jobs]
 * @returns {string[]}
 */
export function listDeclaredNpmScripts(jobs = CI_JOBS) {
  /** @type {Set<string>} */
  const scripts = new Set();

  for (const workflowJob of jobs) {
    for (const workflowStep of workflowJob.steps) {
      if (!('run' in workflowStep)) {
        continue;
      }

      const match = /^npm run ([\w:.-]+)$/.exec(workflowStep.run.trim());

      if (match !== null) {
        scripts.add(match[1]);
      }
    }
  }

  return [...scripts].sort();
}

/**
 * @returns {Promise<string | null>}
 */
async function readWorkflowFile() {
  try {
    return await readFile(new URL(WORKFLOW_FILE, REPOSITORY_ROOT), 'utf8');
  } catch {
    return null;
  }
}

if (isDirectInvocation()) {
  main(process.argv.slice(2)).then(
    (code) => {
      process.exitCode = code;
    },
    (error) => {
      process.exitCode = 1;
      process.stdout.write(
        `${error instanceof Error ? (error.stack ?? error.message) : String(error)}\n`,
      );
    },
  );
}

/**
 * @param {readonly string[]} argv
 * @returns {Promise<number>}
 */
async function main(argv) {
  for (const argument of argv) {
    if (argument !== '--check') {
      throw new Error(`Unknown option: ${argument}`);
    }
  }

  const rendered = renderWorkflowYaml(CI_JOBS);
  const current = await readWorkflowFile();

  if (argv.includes('--check')) {
    if (current !== rendered) {
      process.stdout.write(
        `${WORKFLOW_FILE} is stale; run npm run ci:generate\n`,
      );
      return 1;
    }

    return 0;
  }

  if (current !== rendered) {
    await mkdir(new URL('.github/workflows/', REPOSITORY_ROOT), {
      recursive: true,
    });
    await writeFile(new URL(WORKFLOW_FILE, REPOSITORY_ROOT), rendered);
    process.stdout.write(`${WORKFLOW_FILE}\n`);
  }

  return 0;
}

/**
 * @returns {boolean}
 */
function isDirectInvocation() {
  const entry = process.argv[1];

  return (
    typeof entry === 'string' && pathToFileURL(entry).href === import.meta.url
  );
}
